name: Update quartz
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    uses: ObsidianPublisher/quartz-actions/.github/workflows/update.yml@main
    with:
      AUTO_MERGE: false
    secrets:
      GH_TOKEN: ${{ secrets.GH_PAT }}
